### ISSUE TITLE
Information on gifts

### ISSUE THREAD

**Issue by emanuil-tolev** [Steven-Eardley/wedding#2]
Heya!

Do you have a wedding gifts list? Some people prefer no gifts at all, some leave it at free for all, others have wishlists, etc.

**Comment by Steven-Eardley** [comment]
We do have a wishlist, available for those who request it. I'll send you the URL if you so desire.
We felt uncomfortable putting it on the site as if it's an expectation of ours.

**Comment by emanuil-tolev** [comment]
Ah I see - please do send it on, cheers.
